/**
 * Shared domain types for the SolidGuard MCP server.
 *
 * The pipeline produces "evidence" (deterministic, objective signals) which is
 * fed to an LLM reasoning step. The LLM emits findings + suggestions, which are
 * then verified in a sandbox before being returned to the caller.
 */

export type SolidPrinciple =
  | "SRP"
  | "OCP"
  | "LSP"
  | "ISP"
  | "DIP"
  | "Readability"
  | "Security"
  | "Performance"
  | "Duplication"
  | "Complexity"
  | "Naming"
  | "ErrorHandling";

export type Severity = "critical" | "major" | "minor" | "info";
export type Confidence = "high" | "medium" | "low";

export type FocusArea = "solid" | "security" | "perf" | "readability";

/** Languages the tool can analyze. */
export type LanguageId =
  | "csharp"
  | "typescript"
  | "javascript"
  | "python"
  | "go"
  | "rust"
  | "java"
  | "unknown";

/** A unit of source to review: exactly one of code/filePath/projectPath. */
export interface SourceInput {
  code?: string;
  filePath?: string;
  projectPath?: string;
  /** Optional explicit language; otherwise detected from extension/content. */
  language?: LanguageId;
}

export type DiagnosticSource =
  | "dotnet"
  | "sonar"
  | "roslynator"
  | "metrics"
  | "eslint"
  | "ruff"
  | "golangci"
  | "clippy"
  | "semgrep"
  | "treesitter"
  | "pmd"
  | "generic";

/** A single deterministic diagnostic emitted by an analyzer. */
export interface Diagnostic {
  id: string; // e.g. CA1502, S125, RCS1018
  severity: "error" | "warning" | "info" | "hidden";
  message: string;
  file?: string;
  line?: number;
  column?: number;
  source: DiagnosticSource;
}

/** Code metric for a member, type, or file. */
export interface MetricEntry {
  scope: "assembly" | "namespace" | "type" | "member";
  name: string;
  file?: string;
  line?: number;
  cyclomaticComplexity?: number;
  maintainabilityIndex?: number;
  classCoupling?: number;
  depthOfInheritance?: number;
  linesOfSource?: number;
  linesOfExecutable?: number;
}

/** Aggregated, objective signals handed to the LLM. */
export interface Evidence {
  diagnostics: Diagnostic[];
  metrics: MetricEntry[];
  aggregates: {
    diagnosticCount: number;
    errorCount: number;
    warningCount: number;
    maxCyclomaticComplexity?: number;
    avgMaintainabilityIndex?: number;
    worstMembers: Array<{
      name: string;
      file?: string;
      cyclomaticComplexity?: number;
      maintainabilityIndex?: number;
    }>;
  };
  buildOk: boolean;
  notes: string[];
}

export interface CodeLocation {
  file: string;
  startLine?: number;
  endLine?: number;
  member?: string;
}

/** A reasoned design/quality finding produced by the LLM. */
export interface Finding {
  id: string;
  principle: SolidPrinciple;
  severity: Severity;
  title: string;
  rationale: string;
  location: CodeLocation;
  evidence: string[];
  confidence: Confidence;
}

/** A concrete, file-level refactor proposal. */
export interface Suggestion {
  findingIds: string[];
  file: string;
  newContent: string;
  explanation: string;
}

/** The verification outcome attached to a suggestion. */
export interface VerifiedSuggestion extends Suggestion {
  verified: boolean;
  compileOk: boolean;
  unifiedDiff: string;
  delta: {
    diagnosticsBefore: number;
    diagnosticsAfter: number;
    maxComplexityBefore?: number;
    maxComplexityAfter?: number;
    avgMaintainabilityBefore?: number;
    avgMaintainabilityAfter?: number;
  };
  rejectionReason?: string;
}

export interface ReviewResult {
  score: number; // 0-100, higher is better
  summary: string;
  buildOk: boolean;
  findings: Finding[];
  suggestions: VerifiedSuggestion[];
  metrics: MetricEntry[];
  diagnostics: Diagnostic[];
  notes: string[];
  markdown: string;
}

/** A normalized, analyzable workspace on disk. */
export interface AnalyzableWorkspace {
  /** Language this workspace is prepared for. */
  languageId: LanguageId;
  /** Root directory that contains the project to analyze. */
  rootDir: string;
  /** The entry point used by the language toolchain (e.g. .csproj, dir, file). */
  projectPath: string;
  /** The source files that are the subject of the review. */
  sourceFiles: string[];
  /** True if this workspace was generated by us (and is safe to delete). */
  ephemeral: boolean;
  /** True if we control the project file (so we can inject analyzers/metrics). */
  controlled: boolean;
  /** Cleanup callback. */
  cleanup: () => Promise<void>;
}
