import type { MapInfo } from '../types'

// Real Squad map + layer dataset, limited to AAS and Skirmish layers.
// Each layer's minimap (capture points & lanes baked in) is served from the
// SquadMaps dataset via jsDelivr CDN, pinned to commit 2d6b080095.
// Source: github.com/mahtoid/SquadMaps (Squad Wiki Editorial).
// Generated by .gen_maps.py — do not edit by hand.

export const MAPS: MapInfo[] = [
  {
    id: 'anvil',
    name: 'Anvil',
    sizeMeters: 2100,
    layers: [
      { id: 'Anvil_AAS_v1', name: 'Anvil AAS v1', mode: 'AAS', factions: ['AUS', 'PLA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Anvil_AAS_v1.jpg' },
      { id: 'Anvil_AAS_v2', name: 'Anvil AAS v2', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Anvil_AAS_v2.jpg' },
      { id: 'Anvil_Skirmish_v1', name: 'Anvil Skirmish v1', mode: 'Skirmish', factions: ['AUS', 'RGF'], time: 'Cloudy Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Anvil_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'albasrah',
    name: 'Al Basrah',
    sizeMeters: 1800,
    layers: [
      { id: 'AlBasrah_AAS_v1', name: 'Al Basrah AAS v1', mode: 'AAS', factions: ['USA', 'MEA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/AlBasrah_AAS_v1.jpg' },
      { id: 'AlBasrah_AAS_v2', name: 'Al Basrah AAS v2', mode: 'AAS', factions: ['USA', 'INS'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/AlBasrah_AAS_v2.jpg' },
      { id: 'AlBasrah_AAS_v3', name: 'Al Basrah AAS v3', mode: 'AAS', factions: ['AUS', 'INS'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/AlBasrah_AAS_v3.jpg' },
      { id: 'AlBasrah_Skirmish_v1', name: 'Al Basrah Skirmish v1', mode: 'Skirmish', factions: ['GB', 'MEA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/AlBasrah_Skirmish_v1.jpg' },
      { id: 'AlBasrah_Skirmish_v2', name: 'Al Basrah Skirmish v2', mode: 'Skirmish', factions: ['MIL', 'INS'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/AlBasrah_Skirmish_v2.jpg' },
    ],
  },
  {
    id: 'belaya',
    name: 'Belaya',
    sizeMeters: 2000,
    layers: [
      { id: 'Belaya_AAS_v1', name: 'Belaya AAS v1', mode: 'AAS', factions: ['RGF', 'MIL'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Belaya_AAS_v1.jpg' },
      { id: 'Belaya_AAS_v2', name: 'Belaya AAS v2', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Belaya_AAS_v2.jpg' },
      { id: 'Belaya_AAS_v3', name: 'Belaya AAS v3', mode: 'AAS', factions: ['CAF', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Belaya_AAS_v3.jpg' },
      { id: 'Belaya_Skirmish_v1', name: 'Belaya Skirmish v1', mode: 'Skirmish', factions: ['CAF', 'MIL'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Belaya_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'chora',
    name: 'Chora',
    sizeMeters: 4100,
    layers: [
      { id: 'Chora_AAS_v1', name: 'Chora AAS v1', mode: 'AAS', factions: ['USA', 'MEA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v1.jpg' },
      { id: 'Chora_AAS_v2', name: 'Chora AAS v2', mode: 'AAS', factions: ['USMC', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v2.jpg' },
      { id: 'Chora_AAS_v3', name: 'Chora AAS v3', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v3.jpg' },
      { id: 'Chora_AAS_v4', name: 'Chora AAS v4', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v4.jpg' },
      { id: 'Chora_AAS_v5', name: 'Chora AAS v5', mode: 'AAS', factions: ['CAF', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v5.jpg' },
      { id: 'Chora_AAS_v6', name: 'Chora AAS v6', mode: 'AAS', factions: ['USA', 'PLA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_AAS_v6.jpg' },
      { id: 'Chora_Skirmish_v1', name: 'Chora Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Chora_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'fallujah',
    name: 'Fallujah',
    sizeMeters: 2300,
    layers: [
      { id: 'Fallujah_AAS_v1', name: 'Fallujah AAS v1', mode: 'AAS', factions: ['MEA', 'INS'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Fallujah_AAS_v1.jpg' },
      { id: 'Fallujah_AAS_v2', name: 'Fallujah AAS v2', mode: 'AAS', factions: ['USMC', 'MEA'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Fallujah_AAS_v2.jpg' },
      { id: 'Fallujah_Skirmish_v1', name: 'Fallujah Skirmish v1', mode: 'Skirmish', factions: ['USA', 'MEA'], time: 'Dusty Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Fallujah_Skirmish_v1.jpg' },
      { id: 'Fallujah_Skirmish_v2', name: 'Fallujah Skirmish v2', mode: 'Skirmish', factions: ['USA', 'INS'], time: 'Sand Storm Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Fallujah_Skirmish_v2.jpg' },
    ],
  },
  {
    id: 'foolsroad',
    name: 'Fool\'s Road',
    sizeMeters: 1800,
    layers: [
      { id: 'FoolsRoad_AAS_v1', name: 'Fool\'s Road AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Afternoon', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/FoolsRoad_AAS_v1.jpg' },
      { id: 'FoolsRoad_AAS_v2', name: 'Fool\'s Road AAS v2', mode: 'AAS', factions: ['USA', 'VDV'], time: 'Sunny Afternoon', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/FoolsRoad_AAS_v2.jpg' },
      { id: 'FoolsRoad_Skirmish_v1', name: 'Fool\'s Road Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Sunny Afternoon', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/FoolsRoad_Skirmish_v1.jpg' },
      { id: 'FoolsRoad_Skirmish_v2', name: 'Fool\'s Road Skirmish v2', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Sunny Afternoon', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/FoolsRoad_Skirmish_v2.jpg' },
    ],
  },
  {
    id: 'goosebay',
    name: 'Goose Bay',
    sizeMeters: 3900,
    layers: [
      { id: 'GooseBay_AAS_v1', name: 'Goose Bay AAS v1', mode: 'AAS', factions: ['CAF', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/GooseBay_AAS_v1.jpg' },
      { id: 'GooseBay_AAS_v2', name: 'Goose Bay AAS v2', mode: 'AAS', factions: ['CAF', 'VDV'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/GooseBay_AAS_v2.jpg' },
      { id: 'GooseBay_Skirmish_v1', name: 'Goose Bay Skirmish v1', mode: 'Skirmish', factions: ['CAF', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/GooseBay_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'gorodok',
    name: 'Gorodok',
    sizeMeters: 2000,
    layers: [
      { id: 'Gorodok_AAS_v1', name: 'Gorodok AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Gorodok_AAS_v1.jpg' },
      { id: 'Gorodok_AAS_v2', name: 'Gorodok AAS v2', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Sunset', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Gorodok_AAS_v2.jpg' },
      { id: 'Gorodok_AAS_v3', name: 'Gorodok AAS v3', mode: 'AAS', factions: ['CAF', 'VDV'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Gorodok_AAS_v3.jpg' },
      { id: 'Gorodok_AAS_v4', name: 'Gorodok AAS v4', mode: 'AAS', factions: ['USMC', 'VDV'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Gorodok_AAS_v4.jpg' },
      { id: 'Gorodok_Skirmish_v1', name: 'Gorodok Skirmish v1', mode: 'Skirmish', factions: ['GB', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Gorodok_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'kamdesh',
    name: 'Kamdesh',
    sizeMeters: 2100,
    layers: [
      { id: 'Kamdesh_AAS_v1', name: 'Kamdesh AAS v1', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Stormy', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kamdesh_AAS_v1.jpg' },
      { id: 'Kamdesh_Skirmish_v1', name: 'Kamdesh Skirmish v1', mode: 'Skirmish', factions: ['AUS', 'GB'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kamdesh_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'kohattoi',
    name: 'Kohat Toi',
    sizeMeters: 2100,
    layers: [
      { id: 'Kohat_AAS_v1', name: 'Kohat Toi AAS v1', mode: 'AAS', factions: ['USA', 'PLA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kohat_AAS_v1.jpg' },
      { id: 'Kohat_AAS_v2', name: 'Kohat Toi AAS v2', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Early Morning', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kohat_AAS_v2.jpg' },
      { id: 'Kohat_AAS_v3', name: 'Kohat Toi AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kohat_AAS_v3.jpg' },
      { id: 'Kohat_Skirmish_v1', name: 'Kohat Toi Skirmish v1', mode: 'Skirmish', factions: ['USA', 'GB'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kohat_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'kokan',
    name: 'Kokan',
    sizeMeters: 2500,
    layers: [
      { id: 'Kokan_AAS_v1', name: 'Kokan AAS v1', mode: 'AAS', factions: ['USA', 'PLA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kokan_AAS_v1.jpg' },
      { id: 'Kokan_AAS_v2', name: 'Kokan AAS v2', mode: 'AAS', factions: ['GB', 'MEA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kokan_AAS_v2.jpg' },
      { id: 'Kokan_AAS_v3', name: 'Kokan AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kokan_AAS_v3.jpg' },
      { id: 'Kokan_Skirmish_v1', name: 'Kokan Skirmish v1', mode: 'Skirmish', factions: ['MIL', 'INS'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Kokan_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'lashkar',
    name: 'Lashkar',
    sizeMeters: 2000,
    layers: [
      { id: 'Lashkar_AAS_v1', name: 'Lashkar AAS v1', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Lashkar_AAS_v1.jpg' },
      { id: 'Lashkar_AAS_v2', name: 'Lashkar AAS v2', mode: 'AAS', factions: ['USA', 'MEA'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Lashkar_AAS_v2.jpg' },
      { id: 'Lashkar_AAS_v3', name: 'Lashkar AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Lashkar_AAS_v3.jpg' },
      { id: 'Lashkar_AAS_v4', name: 'Lashkar AAS v4', mode: 'AAS', factions: ['AUS', 'MEA'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Lashkar_AAS_v4.jpg' },
      { id: 'Lashkar_Skirmish_v1', name: 'Lashkar Skirmish v1', mode: 'Skirmish', factions: ['AUS', 'INS'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Lashkar_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'logar',
    name: 'Logar',
    sizeMeters: 1800,
    layers: [
      { id: 'Logar_AAS_v1', name: 'Logar AAS v1', mode: 'AAS', factions: ['USA', 'PLA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Logar_AAS_v1.jpg' },
      { id: 'Logar_AAS_v2', name: 'Logar AAS v2', mode: 'AAS', factions: ['USA', 'MEA'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Logar_AAS_v2.jpg' },
      { id: 'Logar_AAS_v3', name: 'Logar AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Logar_AAS_v3.jpg' },
      { id: 'Logar_Skirmish_v1', name: 'Logar Skirmish v1', mode: 'Skirmish', factions: ['USA', 'MEA'], time: 'Evening', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Logar_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'manicouagan',
    name: 'Manicouagan',
    sizeMeters: 4000,
    layers: [
      { id: 'Manicouagan_AAS_v1', name: 'Manicouagan AAS v1', mode: 'AAS', factions: ['CAF', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_AAS_v1.jpg' },
      { id: 'Manicouagan_AAS_v2', name: 'Manicouagan AAS v2', mode: 'AAS', factions: ['USMC', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_AAS_v2.jpg' },
      { id: 'Manicouagan_AAS_v3', name: 'Manicouagan AAS v3', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_AAS_v3.jpg' },
      { id: 'Manicouagan_AAS_v4', name: 'Manicouagan AAS v4', mode: 'AAS', factions: ['USMC', 'PLANMC'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_AAS_v4.jpg' },
      { id: 'Manicouagan_AAS_v5', name: 'Manicouagan AAS v5', mode: 'AAS', factions: ['USA', 'VDV'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_AAS_v5.jpg' },
      { id: 'Manicouagan_Skirmish_v1', name: 'Manicouagan Skirmish v1', mode: 'Skirmish', factions: ['CAF', 'RGF'], time: 'Stormy', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_Skirmish_v1.jpg' },
      { id: 'Manicouagan_Skirmish_v2', name: 'Manicouagan Skirmish v2', mode: 'Skirmish', factions: ['USMC', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_Skirmish_v2.jpg' },
      { id: 'Manicouagan_Skirmish_v3', name: 'Manicouagan Skirmish v3', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Manicouagan_Skirmish_v3.jpg' },
    ],
  },
  {
    id: 'mestia',
    name: 'Mestia',
    sizeMeters: 2400,
    layers: [
      { id: 'Mestia_AAS_v1', name: 'Mestia AAS v1', mode: 'AAS', factions: ['RGF', 'MIL'], time: 'Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mestia_AAS_v1.jpg' },
      { id: 'Mestia_AAS_v2', name: 'Mestia AAS v2', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunset', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mestia_AAS_v2.jpg' },
      { id: 'Mestia_Skirmish_v1', name: 'Mestia Skirmish v1', mode: 'Skirmish', factions: ['GB', 'MEA'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mestia_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'mutaha',
    name: 'Mutaha',
    sizeMeters: 2800,
    layers: [
      { id: 'Mutaha_AAS_v1', name: 'Mutaha AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mutaha_AAS_v1.jpg' },
      { id: 'Mutaha_AAS_v2', name: 'Mutaha AAS v2', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mutaha_AAS_v2.jpg' },
      { id: 'Mutaha_AAS_v3', name: 'Mutaha AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mutaha_AAS_v3.jpg' },
      { id: 'Mutaha_AAS_v4', name: 'Mutaha AAS v4', mode: 'AAS', factions: ['CAF', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mutaha_AAS_v4.jpg' },
      { id: 'Mutaha_Skirmish_v1', name: 'Mutaha Skirmish v1', mode: 'Skirmish', factions: ['USA', 'MEA'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Mutaha_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'narva',
    name: 'Narva',
    sizeMeters: 1900,
    layers: [
      { id: 'Narva_AAS_v1', name: 'Narva AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Narva_AAS_v1.jpg' },
      { id: 'Narva_AAS_v2', name: 'Narva AAS v2', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Narva_AAS_v2.jpg' },
      { id: 'Narva_AAS_v3', name: 'Narva AAS v3', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Foggy', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Narva_AAS_v3.jpg' },
      { id: 'Narva_AAS_v4', name: 'Narva AAS v4', mode: 'AAS', factions: ['USMC', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Narva_AAS_v4.jpg' },
      { id: 'Narva_Skirmish_v1', name: 'Narva Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Narva_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'skorpo',
    name: 'Skorpo',
    sizeMeters: 2000,
    layers: [
      { id: 'Skorpo_AAS_v1', name: 'Skorpo AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Skorpo_AAS_v1.jpg' },
      { id: 'Skorpo_Skirmish_v1', name: 'Skorpo Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Foggy', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Skorpo_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'sumaribala',
    name: 'Sumari Bala',
    sizeMeters: 1300,
    layers: [
      { id: 'Sumari_AAS_v1', name: 'Sumari Bala AAS v1', mode: 'AAS', factions: ['GB', 'MEA'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_AAS_v1.jpg' },
      { id: 'Sumari_AAS_v2', name: 'Sumari Bala AAS v2', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_AAS_v2.jpg' },
      { id: 'Sumari_AAS_v3', name: 'Sumari Bala AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_AAS_v3.jpg' },
      { id: 'Sumari_AAS_v4', name: 'Sumari Bala AAS v4', mode: 'AAS', factions: ['CAF', 'MEA'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_AAS_v4.jpg' },
      { id: 'Sumari_AAS_v5', name: 'Sumari Bala AAS v5', mode: 'AAS', factions: ['USMC', 'MEA'], time: 'Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_AAS_v5.jpg' },
      { id: 'Sumari_Skirmish_v1', name: 'Sumari Bala Skirmish v1', mode: 'Skirmish', factions: ['USA', 'PLA'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Sumari_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'talliloutskirts',
    name: 'Tallil Outskirts',
    sizeMeters: 4000,
    layers: [
      { id: 'Tallil_AAS_v1', name: 'Tallil Outskirts AAS v1', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Tallil_AAS_v1.jpg' },
      { id: 'Tallil_AAS_v2', name: 'Tallil Outskirts AAS v2', mode: 'AAS', factions: ['USA', 'MEA'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Tallil_AAS_v2.jpg' },
      { id: 'Tallil_Skirmish_v1', name: 'Tallil Outskirts Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Tallil_Skirmish_v1.jpg' },
      { id: 'Tallil_Skirmish_v2', name: 'Tallil Outskirts Skirmish v2', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Morning Sunrise', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Tallil_Skirmish_v2.jpg' },
      { id: 'Tallil_Skirmish_v3', name: 'Tallil Outskirts Skirmish v3', mode: 'Skirmish', factions: ['MIL', 'INS'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Tallil_Skirmish_v3.jpg' },
    ],
  },
  {
    id: 'yehorivka',
    name: 'Yehorivka',
    sizeMeters: 500,
    layers: [
      { id: 'Yehorivka_AAS_v1', name: 'Yehorivka AAS v1', mode: 'AAS', factions: ['GB', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_AAS_v1.jpg' },
      { id: 'Yehorivka_AAS_v2', name: 'Yehorivka AAS v2', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_AAS_v2.jpg' },
      { id: 'Yehorivka_AAS_v3', name: 'Yehorivka AAS v3', mode: 'AAS', factions: ['AUS', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_AAS_v3.jpg' },
      { id: 'Yehorivka_AAS_v4', name: 'Yehorivka AAS v4', mode: 'AAS', factions: ['USMC', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_AAS_v4.jpg' },
      { id: 'Yehorivka_Skirmish_v1', name: 'Yehorivka Skirmish v1', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_Skirmish_v1.jpg' },
      { id: 'Yehorivka_Skirmish_v2', name: 'Yehorivka Skirmish v2', mode: 'Skirmish', factions: ['GB', 'RGF'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_Skirmish_v2.jpg' },
      { id: 'Yehorivka_Skirmish_v3', name: 'Yehorivka Skirmish v3', mode: 'Skirmish', factions: ['USA', 'RGF'], time: 'Partial Clouds Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Yehorivka_Skirmish_v3.jpg' },
    ],
  },
  {
    id: 'blackcoast',
    name: 'Black Coast',
    sizeMeters: 1900,
    layers: [
      { id: 'BlackCoast_AAS_v1', name: 'Black Coast AAS v1', mode: 'AAS', factions: ['USMC', 'VDV'], time: 'Overcast', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/BlackCoast_AAS_v1.jpg' },
      { id: 'BlackCoast_AAS_v2', name: 'Black Coast AAS v2', mode: 'AAS', factions: ['GB', 'MIL'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/BlackCoast_AAS_v2.jpg' },
      { id: 'BlackCoast_Skirmish_v1', name: 'Black Coast Skirmish v1', mode: 'Skirmish', factions: ['USMC', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/BlackCoast_Skirmish_v1.jpg' },
    ],
  },
  {
    id: 'harju',
    name: 'Harju',
    sizeMeters: 3900,
    layers: [
      { id: 'Harju_AAS_v1', name: 'Harju AAS v1', mode: 'AAS', factions: ['USMC', 'VDV'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Harju_AAS_v1.jpg' },
      { id: 'Harju_AAS_v2', name: 'Harju AAS v2', mode: 'AAS', factions: ['USA', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Harju_AAS_v2.jpg' },
      { id: 'Harju_AAS_v3', name: 'Harju AAS v3', mode: 'AAS', factions: ['GB', 'MIL'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Harju_AAS_v3.jpg' },
      { id: 'Harju_Skirmish_v1', name: 'Harju Skirmish v1', mode: 'Skirmish', factions: ['USMC', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Harju_Skirmish_v1.jpg' },
      { id: 'Harju_Skirmish_v2', name: 'Harju Skirmish v2', mode: 'Skirmish', factions: ['CAF', 'RGF'], time: 'Sunny Mid Day', image: 'https://cdn.jsdelivr.net/gh/mahtoid/SquadMaps@2d6b0800952c2fa78a80daed5acfecb8f4fdbb14/img/maps/full_size/Harju_Skirmish_v2.jpg' },
    ],
  },
]

export const MAP_BY_ID = Object.fromEntries(MAPS.map((m) => [m.id, m]))
